name: Deploy no EC2 - WEB

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          echo "${{secrets.KEY_G}}" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ubuntu@ec2-52-71-72-251.compute-1.amazonaws.com "
            cd UboiPOC/ &&
            sudo git pull "
